'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const {validate} = require('../prepare_course_sources.cjs');
const cues = [{id:1,start:0,end:1,en:'Hello Flutter',zh:''}];
const source = {version:1,courseId:1708340,courseSlug:'learn-flutter-dart-to-build-ios-android-apps',sourceLanguage:'en',targetLanguage:'zh-TW',curriculum:[{type:'lecture',id:10,assetType:'Video'},{type:'lecture',id:11,assetType:'Article'},{type:'lecture',id:12,assetType:'Video'}],lectures:[{id:'10',cues,sourceHash:crypto.createHash('sha256').update(JSON.stringify(cues.map(c=>({start:c.start,end:c.end,text:c.en})))).digest('hex')}],errors:[{id:12,error:'No English captions'}]};
assert.equal(validate(source).status,'partial');
assert.equal(validate(source).videoCount,2);
assert.equal(validate(source).cueCount,1);
const altered = structuredClone(source); altered.lectures[0].cues[0].en='Changed';
assert.throws(()=>validate(altered),/hash mismatch/);
const incomplete=structuredClone(source); incomplete.errors=[];
assert.throws(()=>validate(incomplete),/Unreported missing/);
const duplicate=structuredClone(source); duplicate.lectures.push(duplicate.lectures[0]);
assert.throws(()=>validate(duplicate),/duplicate lecture/);
const wrong=structuredClone(source); wrong.courseSlug='codex-the-practical-guide';
assert.throws(()=>validate(wrong),/Unknown course/);
const invalid=structuredClone(source); invalid.lectures[0].cues[0].end=-1;
assert.throws(()=>validate(invalid),/Invalid English cue/);
console.log('PASS: Source hashes, complete video coverage, recorded missing captions, duplicate and removed course rejection.');
